### PR TITLE
Added dotenv support

### PR DESCRIPTION
**Pull request by emir**
Added dotenv support for managing config variables.

(You need to merge first: https://github.com/linna/framework/pull/58)

### CODE REVIEW

**Comment by peter279k** [comment]
It has the [linna-dotenv](https://github.com/linna/dotenv) in this `linna` organization.

@s3b4stian , do we need to use other `dotenv` package?

Also, I think we need to add the `.emv.example` and mention this `.env` usage in `README`.

**Comment by s3b4stian** [comment]
Hello! I am now working on framework, before next release I will update the app, including the dotenv support through [linna-dotenv](https://github.com/linna/dotenv) 👍

**Comment by s3b4stian** [comment]
Anyway, @emir has already do the job, code need only a little touch-up!

**Comment by s3b4stian** [comment]
.env support added in [b0.14.0](https://github.com/linna/app/tree/b0.14.0) with commit [ 2bc7172](https://github.com/linna/app/commit/2bc717268ae7f7df3b69cc3ecc8a2c7f3f6fa9a6) 👍

**Pull request closed without merging**
